{% set version = "1.6.2" %}
{% set sha256 = "9ac4714fa6c315d691da7f5d8941c1b190d4d437397d9742e327c2d51893e373" %}

package:
  name: nim
  version: {{ version }}

source:
  url: https://nim-lang.org/download/nim-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  folder: nim

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rsync
  host:
  run:
    - {{ c_compiler }}_{{ target_platform }}
    - {{ cxx_compiler }}_{{ target_platform }}
    # used by nimble
    - openssl >=1.1
    # used by nimgrep
    - pcre

test:
  commands:
    - command -v nim
    - nim --version
    - nimble --version
    - nimfind --version
    - nimgrep --version
    - nimpretty --version
    - nimsuggest --version
    - '{ testament 2>&1 || true ; } | grep -qxF Usage:'
    - echo 'echo "hello"' >| foo.nim
    - nim c -r foo.nim

about:
  home: https://nim-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Nim programming language, by Andreas Rumpf (araq@)
  description: |
    Nim is a statically typed compiled systems programming language. It combines successful concepts from mature languages like Python, Ada and Modula.
  doc_url: https://nim-lang.org/documentation.html
  dev_url: https://github.com/nim-lang/Nim

extra:
  recipe-maintainers:
    - pb-cdunn
    - btcross26
